approach: Shared Backbone (Pose → Detection)
batch_size: 8
classes:
- helmet
- vest
dataset: C:\Users\ali\Projects\fall_research\unify_ppe\data\new_unify_safety.yaml
detector_base: C:\Users\ali\Projects\fall_research\unify_ppe\models\yolo11s.pt
device: '0'
epochs: 80
pose_backbone_source: C:\Users\ali\Projects\fall_research\unify_ppe\models\yolo11s-pose.pt
trained_model: unified_yolo11s_ppe\det_ppe\weights\best.pt
training_time: '2025-11-16 01:46:53'
